version: "3.5"

x-volumes: &volumes
  - .${WARDEN_WEB_ROOT:-}/pub/media:/var/www/html/pub/media:cached
  - appdata:/var/www/html

services:
  amd:
    platform: linux/amd64
    hostname: "${WARDEN_ENV_NAME}-amd"
    image: warden-php-m2-amd-wk:${PHP_VERSION}
    build:
      context: /opt/warden/utils/warden-php-m2-wk
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
        - PHP_VERSION=${PHP_VERSION}
    volumes: *volumes
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    depends_on:
      - php-fpm
