version: "3.5"

x-volumes: &volumes
  - .${WARDEN_WEB_ROOT:-}/pub/media:/var/www/html/pub/media:cached
  - appdata:/var/www/html

services:
  amd:
    platform: linux/amd64
    hostname: "${WARDEN_ENV_NAME}-amd"
    image: ghcr.io/drpayyne/warden-php-m2:${PHP_VERSION:-7.4}
    volumes: *volumes
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    depends_on:
      - php-fpm
