version: "3.5"

x-volumes: &volumes
  - .${WARDEN_WEB_ROOT:-}/pub/media:/var/www/html/pub/media:cached
  - appdata:/var/www/html

x-environment: &environment
  - CHOWN_DIR_LIST=pub/media ${CHOWN_DIR_LIST:-}

services:
  nginx: { volumes: *volumes }
  php-fpm:
    image: warden-php-m2-wk:${PHP_VERSION}
    build:
      context: /opt/warden/utils/warden-php-m2-wk
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
        - PHP_VERSION=${PHP_VERSION}
    volumes: *volumes
    environment: *environment

  php-debug:
    image: warden-php-m2-wk-xdebug3:${PHP_VERSION}
    build:
      context: /opt/warden/utils/warden-php-m2-xdebug3-wk
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
        - PHP_VERSION=${PHP_VERSION}
    volumes: *volumes
    environment: *environment

volumes:
  appdata:
    name: ${WARDEN_ENV_NAME}-nfsmount
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data/${PWD}"

